# Generated by Django 2.0.2 on 2018-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
