# Generated by Django 2.0.2 on 2018-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180318_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
