# Generated by Django 2.0.2 on 2018-03-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
