# Generated by Django 2.0.2 on 2018-03-05 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('external_id', models.CharField(max_length=255)),
                ('publication', models.ForeignKey(limit_choices_to={'is_publisher': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Article')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_buyer', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(limit_choices_to={'is_publisher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_publication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
