# Generated by Django 2.0.2 on 2018-03-18 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='publication',
            new_name='publisher'

        ),
    ]
