# Generated by Django 2.0.2 on 2018-03-18 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180318_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='publisher',
            field=models.ForeignKey(limit_choices_to={'is_publisher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
