# Generated by Django 2.0.2 on 2018-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180318_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
