# Generated by Django 2.0.2 on 2018-03-19 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_auto_20180318_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='publisher',
        ),
    ]
