# Generated by Django 2.0.2 on 2018-03-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180319_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Fake Title', max_length=255),
            preserve_default=False,
        ),
    ]
